name: Run Invidious Crawler every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *' # 5分ごとに実行
  workflow_dispatch: # 手動実行できるようにもする

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedparser lxml

      - name: Run crawler
        run: |
          python crawler.py
